Creation of ndarray

Write python code to create 3d array in different ways with 15 elements.

Array Creation:

a. Create a 4D NumPy array containing the first 12 positive integers as arr1.

b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.

Find all attributes of array1 and array2

Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy

**1. Write python code to create 3d array in different ways with 15 elements.**

In [98]:
import numpy as np

In [33]:
array = np.array([1,2,3,4,5,6,7,8,9,1,2,3,13,14,15],ndmin=3)

In [34]:
array

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  2,  3, 13, 14, 15]]])

In [8]:
array1 = np.array([1,2,3,4,45,6,7,8,23,24,25,26,27,28,29]).reshape(1,3,5)

In [9]:
array1

array([[[ 1,  2,  3,  4, 45],
        [ 6,  7,  8, 23, 24],
        [25, 26, 27, 28, 29]]])

In [11]:
arr2= np.array([[[1,2,3,4,5,6,7,8,9]]]) 
print(arr2)
arr2.ndim

[[[1 2 3 4 5 6 7 8 9]]]


3

**2. Array Creation:**

a. Create a 4D NumPy array containing the first 12 positive integers as arr1.




In [13]:
array = np.arange(1,13).reshape(1,1,3,4)
print(array)
array.ndim

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]


4

b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.



In [15]:
import random
array = np.random.randint(0,2,20)
array

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1])

**3. Find all attributes of array1 and array2**

In [17]:
array1

array([[[ 1,  2,  3,  4, 45],
        [ 6,  7,  8, 23, 24],
        [25, 26, 27, 28, 29]]])

In [18]:
array1.dtype

dtype('int32')

In [19]:
array1.size

15

In [20]:
array1.nbytes

60

In [21]:
array1.itemsize

4

In [22]:
array.ndim

1

In [23]:
array2 = np.linspace(1,11,20)  
array2

array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
        3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
        6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
        8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ])

In [24]:
array2.itemsize

8

In [25]:
array2.nbytes

160

In [26]:
array2.dtype

dtype('float64')

In [27]:
array2.size

20

**4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.**



In [7]:
array3 = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=3)


In [19]:
array3

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [9]:
array3.ndim

3

In [11]:
array3.dtype

dtype('int32')

In [12]:
array3.size

10

In [13]:
array3.nbytes

40

**Measure of central tendency**



In [20]:
array3.mean()

5.5

In [21]:
np.median(array3)

5.5

**Measure of spread**

In [22]:
Range = array3.max()-array3.min()
Range

9

In [23]:
np.var(array3)

8.25

In [24]:
np.std(array3)

2.8722813232690143

**IQR**

In [25]:
Q1= np.percentile(array3,25)
Q1

3.25

In [26]:
Q2 = np.percentile(array3,50)
Q2

5.5

In [27]:
Q3 = np.percentile(array3,75)
Q3

7.75

In [29]:
IQR = Q3-Q1
IQR

4.5

In [30]:
lower = Q1-(1.5*IQR)
lower

-3.5

In [31]:
upper = Q3+(1.5*IQR)
upper

14.5

In [33]:
print(array3[array3>upper])      #Outlier = no outliers

print(array3[array3<lower])

[]
[]


# Array Slicing and Indexing:

**a. Creating Arrays:**

Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].

Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

**b.Basic Indexing:**

Print the element at index 3 of arr1.

Print the element at row 2, column 1 of arr2

**c. Array Slicing:**

Print the first five elements of arr1.

Print the subarray of arr2 consisting of the last two rows and the first two columns.

Print every second element starting from index 1 up to index 7 of arr1.

In [34]:
arr1= np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr2=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [35]:
arr1[2]

26

In [37]:
arr2[1][1]

4

In [38]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [44]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [47]:
arr1[1: 7: 2]

array([11, 73, 51])

**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:

Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16.

Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

In [50]:
i_arr1= np.array([1,2,3,4,5],dtype ='int16')
f_arr2 = np.array([1,2,3])

In [51]:
i_arr1.dtype

dtype('int16')

In [52]:
f_arr2.dtype

dtype('int32')

**b.Generating Random Numbers:**

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive)

In [53]:
a = np.random.randint(0,101,10)

In [54]:
a

array([54,  4,  7, 91, 83, 86, 10,  6, 64, 66])

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

In [55]:
b = np.random.uniform(-1,1,5)
b

array([ 0.97949604,  0.70291605, -0.58937441,  0.58542005, -0.01517227])

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix.


In [60]:
c = np.random.randint(50,100,16).reshape(4,4)
c

array([[54, 89, 97, 95],
       [59, 96, 87, 95],
       [94, 78, 99, 65],
       [69, 83, 70, 83]])

**4. Apply descriptive statistics for rand_matrix.**



***measure of central tendency***



In [57]:
c.mean()

71.5

In [59]:
np.median(c)

70.0

***Measure of spread***



In [61]:
Range = np.max(c)-np.min(c)
Range

45

In [62]:
np.var(c)

199.93359375

In [63]:
np.std(c)

14.139787613327153

***IQR***

In [65]:
Q1= np.percentile(c,25)
Q1

69.75

In [66]:
Q2 = np.percentile(c,50)
Q2

85.0

In [67]:
Q3 = np.percentile(c,75)
Q3

95.0

In [68]:
IQR= Q3-Q1
IQR

25.25

In [69]:
Lower_limit = Q1-(1.5*IQR)
Lower_limit

31.875

In [70]:
Upper_limit= Q3+(1.5*IQR)
Upper_limit

132.875

In [71]:
print(c[c > Upper_limit])  #Outliers = No outliers
print(c[c< Lower_limit])

[]
[]


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:

How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [102]:
salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

In [104]:
sal = np.array(salaries)

In [105]:
sal

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [91]:
len(sal[sal<50000])

5

In [92]:
np.median(sal)

61699.5

In [93]:
Range= max(sal)- min(sal)
Range

3082388

In [94]:
Q3= np.percentile(sal,75)
m1 = np.mean(sal)
print(Q3)
print(m1)

84496.5
166169.16666666666


In [95]:
sal= sal[(sal > m1) & (sal <=Q3)]
sal

array([], dtype=int32)

In [106]:
q1 = np.percentile(sal,25)

In [107]:
q1

52963.25

In [109]:
len(sal[sal<q1])

8