# Data Cleaning using numpy

The following are the student marks of a class [44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

In [4]:
import numpy as np

In [6]:
array = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])

**Find the no of outliers and missing values?**


In [8]:
np.sum(np.isnan(array))

4

In [9]:
outliers = (array[(array > 100) | (array < 0)])
outliers

array([188., 120., 122.])

**replace the outliers with 45 and missing value with 87.**


In [19]:
array

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [20]:
r = np.where((array > 100) | (array < 0),45,array)   #replacing 45 for outliers
r

array([44., 24., nan, 59., 32., 96., 45., 52., 62., 58., 52., 45., nan,
       nan,  3., 56., 81., 59., 45., 92., nan, 87., 96., 97.,  1., 19.,
        2., 53., 44.])

In [31]:
mis_val = np.where(np.isnan(array),87,r)      #missing value with 87
mis_val

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.])

**what is the average marks of students after 2nd step?**

In [32]:
np.mean(mis_val)

56.96551724137931

**How many students got less than 60 marks?**


In [26]:
mis_val

array([ 44.,  24.,  87.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  87.,  87.,   3.,  56.,  81.,  59., 122.,  92.,  87.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [33]:
students = mis_val[(mis_val <60)]
students

array([44., 24., 59., 32., 45., 52., 58., 52., 45.,  3., 56., 59., 45.,
        1., 19.,  2., 53., 44.])

In [34]:
len(students)

18

**what is the maximum marks?**


In [35]:
max(mis_val)

97.0

**Convert the marks to float32.**


In [36]:
float1 = mis_val.astype('float32')

In [37]:
float1

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

**Solving Linear Equations**

2x + 3y - z = 10

x - y + 2z = 5

3x + 2y + z = 12



Solve the system of equations using NumPy's linalg.solve function.

In [38]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b = np.array([10,5,12])
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

2x + y - z + 3w = 8

3x - 2y + 2z + 2w = 1

x + 3y - 2z + w = 7

4x - y + z - 2w = 3

In [40]:
s = np.array([[2,1,-1,3], [3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])

In [41]:
p = np.array([8,1,7,3])

In [42]:
np.linalg.solve(s,p)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

4x + 2y - 3z = 10

-2x + 3y + z = -3

x - y + 2z = 4

In [44]:
c = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])

In [45]:
d = np.array([10,-3,4])

In [46]:
np.linalg.solve(c,d)

array([2.85365854, 0.6097561 , 0.87804878])

**Conditional Selection with np.where()**

1)Generate a random 1D array A of 10 integers between 1 and 100.

2)Use np.where() to find the indices where the elements of A are greater than 50.

3)Create a new array B that contains elements from A where the condition is met.

4)Calculate the mean of array B and print it along with arrays A and B.

In [49]:
a = np.arange(1,100)

In [50]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
b = np.where((a>50))

In [52]:
b

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
       dtype=int64),)

In [53]:
np.mean(b)

74.0

**Replace Values with np.where()**

1)Create a 4x4 random integer matrix C with values between -10 and 10.

2)Use np.where() to replace all negative values in matrix C with 0.

3)Print the original matrix C and the modified matrix.

In [55]:
r1 = np.random.randint(-10,10,16).reshape(4,4)
r1

array([[ -9,  -2,   7,   9],
       [  7,  -2, -10,  -7],
       [  4,  -2,   0,   2],
       [ -6,   7,  -5,  -5]])

In [56]:
new = np.where((r1<0),0,r1)
new

array([[0, 0, 7, 9],
       [7, 0, 0, 0],
       [4, 0, 0, 2],
       [0, 7, 0, 0]])

In [58]:
print1 = np.stack((r1,new))
print1

array([[[ -9,  -2,   7,   9],
        [  7,  -2, -10,  -7],
        [  4,  -2,   0,   2],
        [ -6,   7,  -5,  -5]],

       [[  0,   0,   7,   9],
        [  7,   0,   0,   0],
        [  4,   0,   0,   2],
        [  0,   7,   0,   0]]])